### ISSUE TITLE
Port [Keras-core] `English-to-Spanish translation` example

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-hub#1189]
We need to Port this existing KerasNLP example to Keras Core

[Keras-io Link](https://keras.io/examples/nlp/neural_machine_translation_with_keras_nlp/)

**Comment by shivance** [comment]
Transformer.fit() fails with following error

<img width="1066" alt="Screenshot 2023-07-30 at 2 52 21 PM" src="https://github.com/keras-team/keras-nlp/assets/51750587/76a5eb6e-4f7e-41c1-bec3-ae50a0f4a956">

**Comment by shivance** [comment]
Awesome @Cyber-Machine !

**Comment by jackd** [comment]
I had a play around and after switching `from tensorflow import keras` to `import keras_core as keras` everything runs fine until training, where there's an issue with masking. I'm unsure if this is an issue of keras_nlp or keras_core.

```
ValueError: Exception encountered when calling Functional.call().

In a nested call() argument, you cannot mix tensors and non-tensors. Received invalid mixed argument: mask=[None, <tf.Tensor 'transformer/NotEqual_1:0' shape=(None, 40) dtype=bool>]

Arguments received by Functional.call():
  • inputs={'encoder_inputs': 'tf.Tensor(shape=(None, 40), dtype=int32)', 'decoder_inputs': 'tf.Tensor(shape=(None, 40), dtype=int32)'}
  • training=True
  • mask={'encoder_inputs': 'None', 'decoder_inputs': 'None'}
  ```

**Comment by vulkomilev** [comment]
@jackd I am ready to help can you please upload your code .

**Comment by jackd** [comment]
@vulkomilev [here's a colab](https://colab.research.google.com/drive/1nX4obfDzNZrqR_OTonXKcdwo1LP6o5Cw?usp=sharing) - asside from some subtle changes to what gets printed, the only difference is `from tensorflow import keras` has been replaced with `import keras_core as keras`. Note this also highlights an issue of possible inconsistent `keras` imports (see cells below `import os` cell).

**Comment by jackd** [comment]
@Cyber-Machine open a PR with an example that raises errors? Seems like this would be a better place to deal with issues...

**Comment by shivance** [comment]
@jackd please open a seperate issue describing the error. Once that's fixed, you could continue porting the example and report more bugs (if any).

**Comment by vulkomilev** [comment]
@jackd 
When I got back to 
from tensorflow import keras
I got this error 
`Traceback (most recent call last):
  File "/home/username/open_source/keras-nlp-main/keras-nlp/copy_of_keras_nlp_eng_spa.py", line 210, in <module>
    x = keras_nlp.layers.TokenAndPositionEmbedding(
  File "/home/username/anaconda3/envs/1195-keras-nlp/lib/python3.10/site-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/username/open_source/keras-nlp-main/keras-nlp/keras_nlp/layers/modeling/token_and_position_embedding.py", line 133, in call
    embedded_positions = self.position_embedding(
  File "/home/username/open_source/keras-nlp-main/keras-nlp/keras_nlp/layers/modeling/position_embedding.py", line 120, in call
    return ops.broadcast_to(position_embeddings, shape)
  File "/home/username/anaconda3/envs/1195-keras-nlp/lib/python3.10/site-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/username/anaconda3/envs/1195-keras-nlp/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling PositionEmbedding.call().

Dimension value must be integer or None or have an __index__ method, got value '<attribute 'shape' of 'numpy.generic' objects>' with type '<class 'getset_descriptor'>'

Arguments received by PositionEmbedding.call():
  • inputs=tf.Tensor(shape=(None, None, 256), dtype=float32)
  • start_index=0
`

**Comment by jackd** [comment]
@vulkomilev not sure why you're getting that, I just re-ran it on colab and it runs fine. Did you reset the runtime after trying it with the `keras_core` version? `keras_nlp` if you've already imported `keras_nlp` with `KERAS_BACKEND` defined then you'll have `keras_nlp` using `keras_core` but `keras` refering to `tensorflow.keras`.

**Comment by vulkomilev** [comment]
![image](https://github.com/keras-team/keras-nlp/assets/79805201/9421a331-f2fe-416d-a913-86f7e1e6d71a)
It looks like one of the masks have a None argument. Tomorrow hopefully I will have it pined down .

**Comment by jackd** [comment]
@vulkomilev I believe the issue at play here is that model calls do not propagate masks, i.e. if `model = keras.Model(a, b); b2 = model(a)` then `b2` will not have a `_keras_mask` even if `b` does.

If you remove the intermediate `encoder` and `decoder` creation/calls the code runs... but the learning curves are significantly different to the tf version, rising to ~25% accuracy part way through the first epoch then slowly dropping. I have no idea as to the cause of this, but have no reason to believe it is due to the masking issue.

**Comment by vulkomilev** [comment]
@jackd 

I have tried to mitigate the issue by deleting the mask attribute
```
delattr(encoder_outputs, "_keras_mask")
decoder_outputs = decoder([decoder_inputs, encoder_outputs])
```
just before the decoder . The decoder_inputs don`t have a mask because inputs don`t have a mask

**Comment by jackd** [comment]
@vulkomilev that's not what I meant. Instead, skip constructing the decoder as a separate model entirely. This way the masking assigned by each `TokenAndPositionEmbedding` propagates through the entire transformer.

```python
encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="encoder_inputs")

x = keras_nlp.layers.TokenAndPositionEmbedding(
    vocabulary_size=ENG_VOCAB_SIZE,
    sequence_length=MAX_SEQUENCE_LENGTH,
    embedding_dim=EMBED_DIM,
    mask_zero=True,
)(encoder_inputs)
encoder_outputs = keras_nlp.layers.TransformerEncoder(
    intermediate_dim=INTERMEDIATE_DIM, num_heads=NUM_HEADS
)(x)

# Decoder
decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="decoder_inputs")

x = keras_nlp.layers.TokenAndPositionEmbedding(
    vocabulary_size=SPA_VOCAB_SIZE,
    sequence_length=MAX_SEQUENCE_LENGTH,
    embedding_dim=EMBED_DIM,
    mask_zero=True,
)(decoder_inputs)

x = keras_nlp.layers.TransformerDecoder(
    intermediate_dim=INTERMEDIATE_DIM, num_heads=NUM_HEADS
)(decoder_sequence=x, encoder_sequence=encoder_outputs)
x = keras.layers.Dropout(0.5)(x)
decoder_outputs = keras.layers.Dense(SPA_VOCAB_SIZE, activation="softmax")(x)

transformer = keras.Model(
    (encoder_inputs, decoder_inputs),
    decoder_outputs,
    name="transformer",
)
```

**Comment by vulkomilev** [comment]
this is also a solution have you tried it @jackd ?

**Comment by jackd** [comment]
@vulkomilev yes
