### ISSUE TITLE
Distributed training not working (batch size calculation)

### ISSUE THREAD

**Issue by natbprice** [keras-team/keras-hub#1630]
**Describe the bug**
This is an issue I am having with keras-nlp, but I am not sure if it can be solved here or should be reported under keras or tensorflow. 

Currently, the batch size is not calculated correctly when performing multi-worker distributed training with JAX backend:

```
Traceback (most recent call last):
  File "mycode.py", line 293, in <module>
    history = classifier.fit(
  File "/usr/local/lib/python3.10/dist-packages/keras_nlp/src/utils/pipeline_model.py", line 194, in fit
    return super().fit(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/distribution/distribution_lib.py", line 467, in distribute_dataset
    raise ValueError(
ValueError: The batch size of the input dataset is unknown. Please config the batch size for the input dataset, e.g via `dataset.batch(batch_size)`
```

**To Reproduce**
Run (multi-worker?) distributed training with JAX backend. 

The issue seems to stem from https://github.com/keras-team/keras-nlp/blob/778ccd72fe5d74e8eedc7d38dfb57561821b7851/keras_nlp/src/utils/pipeline_model.py#L181 where mapping a preprocessor over the dataset leads to failure at https://github.com/keras-team/keras/blob/3105247028bb0a7e6d2f05f5daa44c9cfafd3e67/keras/src/distribution/distribution_lib.py#L465

Here is minimal example where `tensorflow.python.data.experimental.ops.distribute.compute_batch_size()` returns -1 after mapping:
```
import tensorflow as tf
from tensorflow.python.data.experimental.ops import distribute as tf_data_distribute
from keras_nlp.src.utils.keras_utils import pack_x_y_sample_weight

ds = tf.data.Dataset.range(8)
ds = ds.batch(3)

print(f"True batch size (before): {len(list(ds.as_numpy_iterator()))}")
print(f"Calculated batch size (before): {tf_data_distribute.compute_batch_size(ds)}")

ds = ds.map(pack_x_y_sample_weight, num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

print(f"True batch size (after): {len(list(ds.as_numpy_iterator()))}")
print(f"Calculated batch size (after): {tf_data_distribute.compute_batch_size(ds)}")
```

**Expected behavior**
A batched tf.data.Dataset() object is recognized as being batched.

**Comment by natbprice** [comment]
Here is Colab with reproducible example:

https://colab.research.google.com/drive/1aCJVUNfro68fek-o0i_7Iojl6Qtix6NK?usp=sharing

**Comment by natbprice** [comment]
I can reproduce the error using just keras, so maybe I should open issue there? Or maybe it should be fixed in tensorflow? But the documentation for `tensorflow.python.data.experimental.ops.distribute.compute_batch_size()` describes its limitations so not sure it is technically a bug in tensorflow. 

https://colab.research.google.com/drive/1IxVNDcNoIK4SiX2wuDQKfqR_6Or9P40I#scrollTo=0Hf6qJOxXsqI

**Comment by natbprice** [comment]
Hi @SuryanarayanaY, the related ticket in keras was closed with the recommendation that this be fixed in keras-nlp. Per @hertschuh: "One should simply apply batch_size after the map and not in _convert_inputs_to_dataset".

I can't quite figure out the best way for this to work with keras-nlp API. In particular, it seems like there are several combinations of (1) distribution strategy, (2) input types (e.g., tf.data.Dataset, NumPy arrays), and (3) batching (e.g., pre-batched dataset, explicit batch_size).

Currently, in _convert_inputs_to_dataset it will raise an error if you attempt to pass a tf.data.Dataset with explicit batch_size argument. It also looks like there is error handling to prevent you from passing unbatched inputs, but the string matching on the error message may be oudated and not functioning.

**Comment by hertschuh** [comment]
@natbprice ,

Sorry for the delay, I'm still working on this. It turned out to be more complex to fix than I expected.

**Comment by hertschuh** [comment]
@natbprice ,

I experimented with a few things, but I could not find a fix in keras-nlp that would work in all cases.

However, I do have an easy workaround: `ds.batch(8, drop_remainder=True)`. By doing this, the dataset knows that the first dimension, the batch size, is always 8. Then, it can infer the first dimension of the result of other operations like `map`.

If you don't do `drop_remainder=True`, it thinks the last batch may be incomplete. And while you can still retrieve the batch size right after batching, it doesn't propagate through other operations like `map`.

If you're concerned about not using the last few examples, you can `shuffle`, or `repeat` the dataset before batching.

**Comment by natbprice** [comment]
@hertschuh do you have a working example? This doesn't seem to work form me. 

https://colab.research.google.com/drive/1aCJVUNfro68fek-o0i_7Iojl6Qtix6NK?usp=sharing#scrollTo=0Hf6qJOxXsqI

**Comment by natbprice** [comment]
@SuryanarayanaY can we reopen this issue please?

**Comment by maitry63** [comment]
For this issue the bug still persists with latest KerasHub - [gist](https://colab.sandbox.google.com/gist/maitry63/5dd13fb0e74d1411a32a0502f3e1eef1/kerasnlpbug.ipynb#scrollTo=f-Z8wFLxum8c)

**Comment by maitry63** [comment]
Hi @natbprice , After checking into the source code , I found that this is not a bug.  The error happens because in your notebook you  manually changes a private internal variable: `data_parallel._is_multi_process = True`
`_is_multi_process` is an internal attribute and should not be changed manually. 

`Keras` sets this value automatically based on the actual distribution configuration.

By forcing it to `True`,  Keras thinks it is running in a multi-process environment, but the environment is still a normal single-process setup. This triggers the batch size error during dataset distribution.

I tried by removing `manual _is_multi_process` override & training working correctly.

Check this [gist](https://colab.sandbox.google.com/gist/maitry63/5dd13fb0e74d1411a32a0502f3e1eef1/kerasnlpbug.ipynb#scrollTo=NBlgwXC9aLf-).

**Comment by natbprice** [comment]
Hi @maitry63 , thanks for looking into this. I was setting `data_parallel._is_multi_process = True` to mimic a distributed environment in Colab for reproducing the issue. If it is not a distributed environment, then there is no issue.

Can you confirm you tested in a distributed environment and issue is resolved?

Since it has been 2 years, it might also be helpful to test using the original package versions and latest versions.
