### ISSUE TITLE
add weights and conversion script for VGG

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras-hub#1874]
TODO:

- [ ] add weights conversion script here - https://github.com/keras-team/keras-hub/tree/master/tools/checkpoint_conversion
- [ ] Verify output with real inputs
- [ ] provide a working colab demo

Example PR - https://github.com/keras-team/keras-hub/pull/1855.

**Comment by jeffcarp** [comment]
It seems like VGG doesn't currently have any presets configured, is that correct? Did the preset configuration change in the move from KerasCV?

```
>>> import keras_hub
>>> m = keras_hub.models.VGGImageClassifier.from_preset("vgg_16_imagenet")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeffcarp/gh/jeffcarp/keras-hub/keras_hub/src/models/task.py", line 184, in from_preset
    loader = get_preset_loader(preset)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffcarp/gh/jeffcarp/keras-hub/keras_hub/src/utils/preset_utils.py", line 509, in get_preset_loader
    if not check_file_exists(preset, CONFIG_FILE):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffcarp/gh/jeffcarp/keras-hub/keras_hub/src/utils/preset_utils.py", line 264, in check_file_exists
    get_file(preset, path)
  File "/Users/jeffcarp/gh/jeffcarp/keras-hub/keras_hub/src/utils/preset_utils.py", line 225, in get_file
    raise ValueError(
ValueError: Unknown preset identifier. A preset must be a one of:
1) a built-in preset identifier like `'bert_base_en'`
2) a Kaggle Models handle like `'kaggle://keras/bert/keras/bert_base_en'`
3) a Hugging Face handle like `'hf://username/bert_base_en'`
4) a path to a local preset directory like `'./bert_base_en`
Use `print(cls.presets.keys())` to view all built-in presets for API symbol `cls`.
Received: preset='vgg_16_imagenet'
```

**Comment by jeffcarp** [comment]
Oh - or is the point of these scripts to upload the preset weights to Kaggle and add them in KerasHub?
